### ISSUE TITLE
@listen_to is set only to v0x01

### ISSUE THREAD

**Issue by renanrodrigo** [diraol/of_lldp#1]
Somehow it's needed to listen for v0x04 packet_ins and process them as well.

**Comment by diraol** [comment]
Nice catch!

Set the listener to listen to v0x01 and v0x04 is easy: `kytos/of_core.v0x0[14].messages.in.ofpt_packet_in`

But processing the `v0x04` PacketIn will be a little bit more challenging. =)

**Comment by diraol** [comment]
@renanrodrigo I've solved it by adding an `@property` on the `PacketIn` class to retrieve the `in_port` from the right place. =)
